version: "3"
services: 
  mysql_database: 
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: foodcart
    volumes: 
      - ./mysql_scripts:/docker-entrypoint-initdb.d # mysql docker image runs scripts in this folder during initialization of database.
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
    - 8081:80 # host_port:container_port, open localhost:8081 to access phpmyadmin
    environment:
      PMA_HOST: mysql_database 

